In [5]:
from pprint import pprint
import json
f = open("wmt14/wmt14-fr-en-train.json",encoding = "utf-8")
dataset = json.loads(f.read())
print(dataset['dataset'],dataset['split'],dataset['config'])
rows = dataset['rows']
data = []
for row in rows:
    print(row['row_idx'])
    tgt = row['row']['translation']['fr']
    src = row['row']['translation']['en']
    print(src, tgt)


wmt14 train fr-en
0
Resumption of the session Reprise de la session
1
I declare resumed the session of the European Parliament adjourned on Friday 17 December 1999, and I would like once again to wish you a happy new year in the hope that you enjoyed a pleasant festive period. Je déclare reprise la session du Parlement européen qui avait été interrompue le vendredi 17 décembre dernier et je vous renouvelle tous mes vux en espérant que vous avez passé de bonnes vacances.
2
Although, as you will have seen, the dreaded 'millennium bug' failed to materialise, still the people in a number of countries suffered a series of natural disasters that truly were dreadful. Comme vous avez pu le constater, le grand "bogue de l'an 2000" ne s'est pas produit. En revanche, les citoyens d'un certain nombre de nos pays ont été victimes de catastrophes naturelles qui ont vraiment été terribles.
3
You have requested a debate on this subject in the course of the next few days, during this part-session. Vous

In [6]:
from datasets import load_dataset
dataset = load_dataset("tatoeba", lang1="en", lang2="he", date="v2020-11-09")
print(dataset)

TypeError: TextConfig.__init__() got an unexpected keyword argument 'lang1'

In [7]:
fd = open("/home/yang/github/fuzzys2s/doc/tatoeba/fra.txt",encoding = "utf-8")
lines = fd.readlines()

for line in lines[:10]:
    sentences = line.split("\t")
    en = sentences[0]
    fra = sentences[1]
    print("en:", en, "fra:", fra)
    

en: Go. fra: Va !
en: Go. fra: Marche.
en: Go. fra: En route !
en: Go. fra: Bouge !
en: Hi. fra: Salut !
en: Hi. fra: Salut.
en: Run! fra: Cours !
en: Run! fra: Courez !
en: Run! fra: Prenez vos jambes à vos cous !
en: Run! fra: File !


In [5]:
import numpy as np
tokens = np.empty(5, dtype = int)
tokens.fill(7)
print(tokens)
arr = np.array([[1,2,3], [1,2,3]])
print(arr)

[7 7 7 7 7]
[[1 2 3]
 [1 2 3]]
