In [17]:
import torch
from torch import nn
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class Weight(nn.Module):
    def __init__(self):
        super(Weight, self).__init__()
        self.w = nn.Parameter(torch.tensor([0.5]))
        self.delta = nn.Parameter(torch.randn(8,8))
    def forward(self,x):
        output = x + self.delta[0]
        return output*self.w

class MLP(nn.Module):
    def __init__(self,feature_num , rule_num, center,sigma ):
        super(MLP, self).__init__()
        self.fc = nn.Linear(feature_num, 32)
        self.relu = nn.ReLU()
        self.drop_out= nn.Dropout(0.1)
        self.fc2 = nn.Linear(32, 16)
        self.relu2 = nn.ReLU()
        self.drop_out2= nn.Dropout(0.1)
        self.fc3 = nn.Linear(16, 8)
        self.weight = Weight()
    def forward(self, x):
        input = self.fc(x)
        input = self.relu(input)
        input = self.drop_out(input)
        input = self.fc2(input)
        input = self.relu2(input)
        input = self.drop_out2(input)
        output = self.fc3(input)
        return self.weight(output)

In [ ]:
features = torch.randn((100, 13))
target = torch.randint(0,5, (100,1))

mlp = MLP(13,10, "","")
optimizer = torch.optim.Adam(mlp.parameters(), lr=0.0001, weight_decay=0)
criterion = nn.CrossEntropyLoss()
for i in range(100):
    x = torch.tensor(features[i])
    target = torch.tensor(target[i]).squeeze()
    output = mlp(x)
    loss = criterion(output, target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    for name, parms in mlp.named_parameters():
        print('-->name:', name)
        # print('-->para:', parms)
        print('-->grad_requirs:',parms.requires_grad)
        print('-->grad_value:',parms.grad)

In [31]:
x = torch.tensor([0,1,2,3,4,5,6,7])
# x = x.view(1,-1)
print(x)
x_arr = x.repeat(1, 10).view(-1, 8)
print(x_arr)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]])


In [2]:
import torch
rule = torch.tensor([1,2,3,4,5,6,7,8,9,10])
memory = torch.tensor([2,2,3,4,4,4,4,4,4,4])
recurrent_weight = torch.tensor([0.1,0.1, 0.1,0.1,0.1,0.1, 0.1,0.1,0.1,0.1])
recurrent_memory = torch.mul(memory, recurrent_weight)
print(recurrent_memory)
rule = torch.mul(rule, recurrent_memory)
print(rule)

tensor([0.2000, 0.2000, 0.3000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000, 0.4000,
        0.4000])
tensor([0.2000, 0.4000, 0.9000, 1.6000, 2.0000, 2.4000, 2.8000, 3.2000, 3.6000,
        4.0000])
